### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by fjgaston** [tarsjoris/x-air#17]
Hi,
I'm not sure if doing it right. On my mac, I first installed maven and npm with brew. Then I run ./build.sh then I have build failure.
But I'm not familiar with java, npm and mvn so maybe I'm doing everything wrong ?

**Comment by tarsjoris** [comment]
Hi fjgaston,
What is the build failure? Does the script report an error?

**Comment by tarsjoris** [comment]
No reaction, so closing.
